# Bound Expansion Test Configuration (Small-Scale)
# Purpose: Quickly exercise auto bound expansion logic with narrow initial ranges

ModelParameters:
  β: 0.996
  δ: 0.011
  γ₀: 1.0
  γ₁: 0.7668
  κ₁: 1.0
  A₀: 0.0
  A₁: 1.0
  b: 0.4
  ξ: 0.2
  κ₀: 100.0   # placeholder baseline
  ψ₀: 0.75
  ϕ: 0.5
  ν: 0.4
  c₀: 5.0
  χ: 8.0
  aₕ: 2.0
  bₕ: 5.0
  μ: 0.05

ModelGrids:
  n_ψ: 60
  ψ_min: 0.0
  ψ_max: 1.0
  ψ_data: /project/high_tech_ind/searching-flexibility/data/results/psi_distribution_Post_COVID.csv
  ψ_column: psi
  ψ_weight: probability_mass
  n_h: 81
  h_min: 0.05
  h_max: 1.0

ModelSolverOptions:
  tol: 1e-5         # relaxed for speed
  max_iter: 5_000   # smaller for fast test
  verbose: false
  print_freq: 200
  lambda_S_init: 0.01
  lambda_u_init: 0.01
  initial_S: null

MPISearchConfig:
  algorithm: "genetic_algorithm"
  n_samples: 5000   # not used directly by GA but kept for compatibility
  parameters:
    names: ["aₕ", "bₕ", "c₀", "μ", "χ", "ν", "ψ₀", "ϕ", "κ₀"]
    bounds:
      # Deliberately narrow a subset of bounds to trigger expansions
      aₕ: [1.5, 2.0]
      bₕ: [4.5, 5.5]
      μ:  [0.04, 0.06]
      c₀: [0.0005, 4.0]
      χ:  [0.0005, 25.0]
      ν:  [0.01, 5.0]
      ψ₀: [0.0, 0.999]
      ϕ:  [0.01, 5.0]
      κ₀: [1.0, 120.0]

  target_moments:
    data_file: "data/results/data_moments/data_moments_2024.yaml"
    moments_to_use: [
      "var_logwage",
      "mean_alpha",
      "var_alpha",
      "inperson_share",
      "remote_share",
      "p90_p10_logwage",
      "diff_alpha_high_lowpsi",
      "wage_premium_high_psi",
      "wage_slope_psi",
      "market_tightness"
    ]

  moment_computation:
    method: "simulation"
    simulated_data: "data/processed/simulation_scaffolding_2024.feather"

  search_options:
    population_size: 16          # small for quick test
    mutation_rate: 0.25
    crossover_rate: 0.8
    n_generations: 5             # very small run
    elite_fraction: 0.125
    auto_bound_expansion:
      enabled: true
      edge_fraction: 0.05          # broader edge band for small pop
      min_generations: 2           # trigger quickly for test
      population_edge_share: 0.25  # 25% at edge
      expansion_factor: 2.0        # double the range in that direction
      max_expansions_per_param: 3
      global_upper_caps:
        κ₀: 600.0
      global_lower_caps:
        c₀: 0.0001
    sampling_method: "sobol"
    batch_size: 200
    n_initial_points: 30
    acquisition_function: "expected_improvement"

  output:
    results_dir: "output/mpi_search_results"
    checkpoint_frequency: 50
    save_all_results: false
    detailed_logging: true

  performance:
    timing_diagnostics: true
    memory_monitoring: true
    convergence_tracking: true
