### Ground-Truth Recovery Experiment Config
# Points target_moments.data_file to synthetic moments produced by prepare_ground_truth_experiment.jl

ModelParameters:
  β: 0.996
  δ: 0.011
  γ₀: 1.0
  γ₁: 0.7668
  κ₁: 1.0
  A₀: 0.0
  A₁: 1.0
  b: 0.4
  ξ: 0.2
  κ₀: 850.0
  ψ₀: 0.75
  ϕ: 0.5
  ν: 0.4
  c₀: 5.0
  χ: 8.0
  aₕ: 2.0
  bₕ: 5.0
  μ: 0.05

ModelGrids:
  n_ψ: 100
  ψ_min: 0.0
  ψ_max: 1.0
  ψ_data: /project/high_tech_ind/searching-flexibility/data/results/psi_distribution_Post_COVID.csv
  ψ_column: psi
  ψ_weight: probability_mass
  n_h: 101
  h_min: 0.05
  h_max: 1.0

ModelSolverOptions:
  tol: 1e-6
  max_iter: 25000
  verbose: false
  print_freq: 100
  lambda_S_init: 0.01
  lambda_u_init: 0.01
  initial_S: null

MPISearchConfig:
  algorithm: "genetic_algorithm"
  n_samples: 100000
  parameters:
    names: ["aₕ", "bₕ", "c₀", "μ", "χ", "ν", "ψ₀", "ϕ", "κ₀"]
    bounds:
      c₀: [0.0001, 2.0]
      μ:  [0.0001, 0.2]
      κ₀: [1.0, 300.0]
      aₕ: [0.01, 2.0]
      bₕ: [0.01, 2.0]
      χ: [4.0, 12.0]
      ν: [0.01, 1.0]
      ψ₀: [0.01, 1.0]
      ϕ: [0.5, 1.5]
  target_moments:
    data_file: "data/results/data_moments/data_moments_groundtruth_2024.yaml"
    moments_to_use:
      - var_logwage
      - mean_alpha
      - var_alpha
      - inperson_share
      - remote_share
      - p90_p10_logwage
      - diff_alpha_high_lowpsi
      - wage_premium_high_psi
      - market_tightness
      - wage_alpha
      - wage_alpha_curvature
  moment_computation:
    method: "simulation"
    simulated_data: "data/processed/simulation_scaffolding_2024.feather"
  search_options:
    population_size: 320
    mutation_rate: 0.22
    mutation_scale: 0.12
    crossover_rate: 0.85
    n_generations: 120
    elite_fraction: 0.08
    tournament_size: 3
    early_stopping:
      enabled: true
      patience: 20
      min_improvement: 5e-5
      mode: "absolute"
      warmup_generations: 15
    auto_bound_expansion:
      enabled: true
      edge_fraction: 0.02
      population_edge_share: 0.18
      min_generations: 8
      expansion_factor: 1.6
      max_expansions_per_param: 6
      global_upper_caps:
        κ₀: 600.0
      global_lower_caps:
        c₀: 0.00005
        aₕ: 0.000001
        bₕ: 0.000001
  output:
    results_dir: "src/structural_model_heterogenous_preferences/distributed_mpi_search/output/results"
    checkpoint_frequency: 1000
    save_all_results: false
    detailed_logging: true
  valid_objectives_csv_template: "src/structural_model_heterogenous_preferences/distributed_mpi_search/output/results/mpi_search_results_job{job_id}_valid_objectives.csv"
  performance:
    timing_diagnostics: true
    memory_monitoring: true
    convergence_tracking: true
